sudo: false

language: java
jdk: oraclejdk8

before_install:
  - unset _JAVA_OPTIONS

jobs:
  include:
# starter
    - stage: starter
      env: TOOL='Gradle'
      env: TOPIC='Kotlin'
      script: cd $TRAVIS_BUILD_DIR && ./gradle test --console plain
