sudo: false

language: java
jdk: oraclejdk8

before_install:
  - unset _JAVA_OPTIONS
  - chmod +x gradlew

jobs:
  include:
# starter
    - stage: starter
      name: "Jupiter Starter Sample: Gradle & Kotlin"
      script: cd $TRAVIS_BUILD_DIR && ./gradlew test --console plain

